language: node_js
node_js:
  - "9"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  on:
    branch: dev
