language: node_js
node_js:
  - "9"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run build
deploy:
  # deploy to sreejagpt.github.io and push build output to master branch
  - provider: script
    script: npm run deploy
    on:
      branch: develop
